### ISSUE TITLE
Non-aliased version of RtlMoveMemory?

### ISSUE THREAD

**Issue by GCuser99** [fafalone/WinDevLib#20]
I noticed that you have the common aliases for RtlMoveMemory in WDL, but not the unaliased version. Shouldn't that be in there too?

Thanks!

**Comment by fafalone** [comment]
Yup good point, I'll add them in the next update tonight.

**Comment by fafalone** [comment]
There are now non-aliased versions of RtlMoveMemory, RtlZeroMemory, and RtlZeroMemory in WinDevLib v7.9.390, available now. Thanks for the suggestion!
