### ISSUE TITLE
WDL Conversion Question

### ISSUE THREAD

**Issue by GCuser99** [fafalone/WinDevLib#24]
Jon, sorry for taking up your time, but I'm needing some clarification on how to switch my code to be WDL-compatible. I read your ReadMe and initially thought I understood, but am still having some issues. 

How would I convert from my current usage to WDL usage given the declare and usage example blocks below? Passing vbNullPtr to the pCaller and IpfnCB arguments causes a compile error. Is passing NULL ok? I tested NULL and it seems to work, but I did not see explicit mention of that in your ReadMe.

```vba
'Legacy declare:
Public Declare PtrSafe Function UrlDownloadToFile Lib "urlmon" Alias "URLDownloadToFileW" ( _
    ByVal pCaller As Long, _
    ByVal szURL As LongPtr, _
    ByVal szFileName As LongPtr, _
    ByVal dwReserved As Long, _
    ByVal lpfnCB As Long) As Long

'WDL declare:
Public DeclareWide PtrSafe Function UrlDownloadToFile Lib "urlmon" Alias "URLDownloadToFileW" ( _
    ByVal pCaller As stdole.IUnknown, _
    ByVal szURL As String, _
    ByVal szFile As String, _
    ByVal dwReserved As Long, _
    ByVal lpfnCB As IBindStatusCallback) As Long
```

```vba
'Legacy usage:
ret = UrlDownloadToFile(0&, StrPtr(Url), StrPtr(filePath), 0&, 0&)

'WDL usage??? This seems to work but is it correct?
ret = UrlDownloadToFile(Null, Url, filePath, 0&, Null)
```

Thanks!

**Comment by GCuser99** [comment]
Edit: Passing Null does not work. Crashes app.

**Comment by fafalone** [comment]
`Nothing` is the proper thing to pass for an optional ByVal interface you're not using.

Null is misleading; it's a special Variant thing, doesn't work with anything else.

**Comment by GCuser99** [comment]
That makes sense, now that you point it out. I don't know why I didn't think of it. Thanks Jon!

**Comment by GCuser99** [comment]
It might be helpful to add a note for novices like me in your (very excellent BTW!) Readme that:
 "You should pass ```Nothing``` to an optional argument ```ByVal [Interface]``` that you are not using".

**Comment by fafalone** [comment]
I'll add that and try to make the section clearer, thanks for the feedback. 👍
