### ISSUE TITLE
GetAsyncKeyState and GetKeyState Argument Type

### ISSUE THREAD

**Issue by GCuser99** [fafalone/WinDevLib#31]
Not a bug, but perhaps a minor improvement since it looks like you have the VirtualKeyCodes Enum defined:
```vba
'Currently in WDL:
Public DeclareWide PtrSafe Function GetAsyncKeyState Lib "user32" (ByVal VKey As Long) As Integer
Public DeclareWide PtrSafe Function GetKeyState Lib "user32" (ByVal nVirtKey As Long) As Integer

'Proposed changes:
Public Declare PtrSafe Function GetAsyncKeyState Lib "user32" (ByVal VKey As VirtualKeyCodes) As Integer
Public Declare PtrSafe Function GetKeyState Lib "user32" (ByVal nVirtKey As VirtualKeyCodes) As Integer
```

**Comment by fafalone** [comment]
But that's what it is already? And has been as far back as I checked (v5.2)

**Comment by GCuser99** [comment]
Oh, you are right! Looks like I was looking at the wrong tB package (WindowsAPI.twin in WInNativeCommonCtls). Sorry about that!

**Comment by fafalone** [comment]
No worries, happens to all of use. Definitely report these kinds of things for APIs. I know in some of the interface sections some work needs to be done with these substitutions; mostly the large media sets like MediaFoundation, CoreAudio, and DirectX where I didn't do it a long time ago in oleexp and imported in bulk from there. So those don't worry, known issue, but APIs, other interface sets? Sure, when you come across them-- don't worry about going looking deliberately.

Can't wait for TypeHint to be allowed in UDTs, as you've probably seen I've been provisioning for a long time now to associate enums with non-Long members 😄
