### ISSUE TITLE
SHCreateItemFromParsingName overload?

### ISSUE THREAD

**Issue by GCuser99** [fafalone/WinDevLib#34]
Jon, did you intend to overload this one?
```vba
Public DeclareWide PtrSafe Function SHCreateItemFromParsingName Lib "shell32" (ByVal pszPath As String, ByVal pbc As IBindCtx, riid As UUID, ppv As Any) As Long
Public DeclareWide PtrSafe Function SHCreateItemFromParsingName Lib "shell32" (ByVal pszPath As LongPtr, ByVal pbc As IBindCtx, riid As UUID, ppv As Any) As Long
```

**Comment by fafalone** [comment]
Yes that and some other common ones I've been experimenting with overloads so you can either pass a string directly or StrPtr/LongPtr. Have you encountered any issues with tB resolving the correct one to use?

**Comment by GCuser99** [comment]
No, it works fine - just checking... thx
