### ISSUE TITLE
Windevlib SHOpenFolderAndSelectItems statement in error

### ISSUE THREAD

**Issue by forliny** [fafalone/WinDevLib#35]
In windevlib SHOpenFolderAndSelectItems statement is as follows:
Public Declare PtrSafe Function SHOpenFolderAndSelectItems Lib "shell32" (ByVal pidlFolder As LongPtr, ByVal cidl As Long, ByVal apidl As LongPtr, ByVal dwFlags As SHOFASI_Flags) As Long

This declaration, lead to open an empty folder, not the inside of the selected file lngRet = SHOpenFolderAndSelectItems (lngPidl, 1, lngPidl, 0) program crashes.

apidl is an array parameter, so the correct declaration should be

Public Declare PtrSafe Function SHOpenFolderAndSelectItems Lib "shell32" (ByVal pidlFolder As LongPtr, ByVal cidl As Long, ByRef apidl As  LongPtr, ByVal dwFlags As SHOFASI_Flags) As Long

At this point, the use of lngRet = SHOpenFolderAndSelectItems (lngPidl , 1 , lngPidl , 0), the right to open a folder.

**Comment by fafalone** [comment]
It was that way for compatibility with... something... I don't recall. I know one of my other sample programs but I vaguely remember basing that on some other example.

`lngRet = SHOpenFolderAndSelectItems (lngPidl, 1, VarPtr(lngPidl), 0)`

will work with the original declaration. If I change it now, it breaks various things using VarPtr... not sure what to do; don't think an overload would work well.

**Comment by fafalone** [comment]
It's been changed to `ByRef apidl As LongPtr` now as of 8.6.470.

An overload would be unresolvable so existing code using VarPtr will need to be changed to add `ByVal` or remove `VarPtr`.
